import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://pv02.extendedcare.health/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Log In' }).click();
  const page1 = await page1Promise;
  await page1.locator('#UserNameTextBox').fill('srikannan');
  await page1.locator('#UserNameTextBox').press('Tab');
  await page1.locator('#PasswordTextBox').fill('Organization=20');
  await page1.getByText('Log In').click();
  await page1.getByRole('link', { name: ' Home' }).click();
  await page1.getByRole('link', { name: 'Change Organization' }).click();
  await page1.getByRole('link', { name: 'CM Automation Hospital', exact: true }).click();
  await page1.getByRole('link', { name: ' Manage' }).click();
  await page1.getByRole('link', { name: 'Patients ' }).click();
  await page1.getByRole('link', { name: 'Patients Default View' }).click();
  //Add a Patient
  await page1.getByRole('link', { name: 'Add a Patient' }).click();
  await page1.getByLabel('MRN:').click();
  await page1.getByLabel('MRN:').fill('Automate_4');
  await page1.getByLabel('First Name:', { exact: true }).click();
  await page1.getByLabel('First Name:', { exact: true }).fill('Test_Printable Docs');
  await page1.getByLabel('Last Name:', { exact: true }).click();
  await page1.getByLabel('Last Name:', { exact: true }).fill('& Attachments');
  await page1.locator('#ECINCalendarDateOfBirth_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '15', exact: true }).click();
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('link', { name: '' }).click();
  //Add Admission
  await page1.locator('#txtHospitalAdmissionID').click();
  await page1.locator('#txtHospitalAdmissionID').fill('Acc_PD_2');
  await page1.locator('#dtPatientAdmission_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').locator('#selYear').selectOption('97');
  await page1.frameLocator('iframe[name="CalIFrame"]').locator('#Cell31').click();
  await page1.locator('#dtPatientAdmission_Time').click();
  await page1.locator('#dtPatientAdmission_Time').fill('12:50 PM');
  await page1.locator('#txtPrimaryDiagnosis').click();
  await page1.locator('#txtPrimaryDiagnosis').fill('Stomach Infection');
  await page1.getByRole('button', { name: 'Save' }).click();
  
  //Navigation to Printable Documents
  await page.locator('li').filter({ hasText: 'Printable Documents Admission' }).locator('i').first().click();
  await page.getByRole('link', { name: 'Admission Timeline' }).click();
  await expect(page.getByRole('cell', { name: '7/9/2024 12:40 PM (CT)', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Call List' }).click();
  await page.locator('#RptCalendar_FromDate_CalImg').click();
  await page.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '14', exact: true }).click();
  await page.locator('#RptCalendar_ToDate_CalImg').click();
  await page.frameLocator('iframe[name="CalIFrame"]').locator('#selYear').selectOption('106');
  await page.getByRole('button', { name: 'Generate' }).click();
  await page.locator('#RptCalendar_ToDate_CalImg').click();
  await page.frameLocator('iframe[name="CalIFrame"]').locator('#selYear').selectOption('103');
  await page.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '17', exact: true }).click();
  await page.getByRole('button', { name: 'Generate' }).click();
  await page.locator('#RptCalendar_FromDate_CalImg').click();
  await page.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '2024', exact: true }).click();
  await page.frameLocator('iframe[name="CalIFrame"]').locator('#selYear').selectOption('116');
  await page.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '13', exact: true }).click();
  await page.locator('#RptCalendar_ToDate_CalImg').click();
  await page.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '18', exact: true }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Generate' }).click();
  const page1 = await page1Promise;
  await expect(page1.getByText('/9/2024 12:40 PM (CT)')).toBeVisible();
  await expect(page1.getByText('-- 9/13/2024 12:47:36 AM')).toBeVisible();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Discharge Summary' }).click();
  const page2 = await page2Promise;
  await page.goto('https://pv02.extendedcare.health/professional/Reports/PatientDocuments/PrintableDischargeSummaryLaunch.aspx');
  await expect(page2.getByText('/9/2024 12:40 PM (CT)')).toBeVisible();
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Patient Information' }).click();
  const page3 = await page3Promise;
  await page.goto('https://pv02.extendedcare.health/professional/Reports/PatientDocuments/PatientInformationLaunch.aspx');
  await expect(page3.getByRole('cell', { name: '7/9/2024 12:40 PM (CT)', exact: true })).toBeVisible();
  await expect(page3.getByRole('cell', { name: '8/9/2024 12:30 PM (CT)', exact: true })).toBeVisible();
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Review History' }).click();
  const page4 = await page4Promise;
  await page.goto('https://pv02.extendedcare.health/professional/Reports/PatientDocuments/ReviewHistoryLaunch.aspx');
  await expect(page4.getByRole('cell', { name: '7/9/2024 12:40 PM (CT)', exact: true })).toBeVisible();
  await expect(page4.getByText('-- 9/13/2024 12:50:06 AM')).toBeVisible();
});