import { test, expect } from '@playwright/test';

test('CM- HCA to Support4', async ({ page }) => {
  await page.goto('https://pv02.extendedcare.health/professional/home/logon.aspx');
  await page.locator('#UserNameTextBox').click();
  await page.locator('#UserNameTextBox').fill('srikannan');
  await page.locator('#UserNameTextBox').press('Tab');
  await page.locator('#PasswordTextBox').fill('Organization=20');
  await page.getByText('Log In').click();
  await page.getByRole('link', { name: ' Home' }).click();
  await page.getByRole('link', { name: 'Change Organization' }).click();
  await page.getByRole('link', { name: '`Allscripts QA Hospital 124 (' }).click();
  await page.getByRole('link', { name: ' Manage' }).click();
  await page.getByRole('link', { name: 'Patient Favorites ' }).click();
  await page.getByRole('link', { name: 'Patient Favorites ' }).click();
  await page.getByRole('link', { name: 'M R, SRIKANNAN (974246)' }).click();
  await page.getByRole('link', { name: 'TEST12345 (7/9/2024)' }).click();
  await page.getByRole('link', { name: 'Assessment / Needs' }).click();
  await page.getByRole('link', { name: 'DME General' }).click();
  await expect(page.locator('#dteDeliveryDate_Date')).toBeVisible();
  await page.getByRole('link', { name: 'Functional Status - Current' }).click();
  await expect(page.locator('#ECINCalendarAsOf_Date')).toBeVisible();
  await page.getByRole('link', { name: 'Functional Status - Initial' }).click();
  await expect(page.locator('#ECINCalendarAsOf_Date')).toBeVisible();
  await page.getByRole('link', { name: 'Functional Status - Pre-' }).click();
  await expect(page.locator('#ECINCalendarAsOf_Date')).toBeVisible();
  await page.getByRole('link', { name: 'Newborn Information' }).click();
  await expect(page.locator('#ECINCalendar1_Date')).toBeVisible();
  await expect(page.getByRole('cell', { name: '8:40 PM (GMT)', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Home Care' }).click();
  await expect(page.locator('#dteStartDateOfCare_Date')).toBeVisible();
  await expect(page.locator('#dteStartDateOfCare_Time')).toBeVisible();
  await expect(page.getByRole('cell', { name: '8:40 PM (GMT)', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Respiratory' }).click();
  await expect(page.getByRole('cell', { name: '8/30/2024', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Vital Signs' }).click();
  await expect(page.locator('#dtStartDate_Date')).toBeVisible();
  await expect(page.locator('#dtEndDate_Date')).toBeVisible();
  await page.getByRole('link', { name: 'Transportation' }).click();
  await expect(page.locator('#calTransportDate_Date')).toBeVisible();
  await page.getByRole('link', { name: 'Allergies / Medications' }).click();
  await expect(page.getByRole('cell', { name: '9/3/2024', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: '9/2/2024', exact: true })).toBeVisible();
});