import { test, expect } from '@playwright/test';

test('CM- HCA to Support', async ({ page }) => {
  await page.goto('https://pv02.extendedcare.health/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Log In' }).click();
  const page1 = await page1Promise;
  await page1.locator('#UserNameTextBox').fill('srikannan');
  await page1.locator('#PasswordTextBox').click();
  await page1.locator('#PasswordTextBox').fill('Organization=20');
  await page1.getByText('Log In').click();
  await page1.getByRole('link', { name: ' Home' }).click();
  await page1.getByRole('link', { name: 'Change Organization' }).click();
  await page1.getByRole('link', { name: '`Allscripts QA Hospital 124 (' }).click();
  await page1.getByRole('link', { name: ' Manage' }).click();
  await page1.getByRole('link', { name: 'Patients ' }).click();
  await page1.getByRole('link', { name: 'Patients Default View' }).click();
  await page1.getByRole('link', { name: 'Add a Patient' }).click();
  await page1.getByLabel('MRN:').click();
  await page1.getByLabel('MRN:').fill('123456');
  await page1.getByLabel('First Name:', { exact: true }).click();
  await page1.getByLabel('First Name:', { exact: true }).fill('sri');
  await page1.getByLabel('Last Name:', { exact: true }).click();
  await page1.getByLabel('Last Name:', { exact: true }).fill('kannan');
  await page1.locator('#ECINCalendarDateOfBirth_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '11', exact: true }).click();
  await page1.getByLabel('Sex at Birth:').selectOption('1');
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('link', { name: '' }).click();
  await page1.getByLabel('Create Admission').check();
  await page1.getByRole('button', { name: 'Ok' }).click();
  await page1.locator('#txtHospitalAdmissionID').click();
  await page1.locator('#txtHospitalAdmissionID').fill('adm123');
  await page1.locator('#dtPatientAdmission_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '12', exact: true }).click();
  await page1.locator('#dtPatientAdmission_Time').click();
  await page1.locator('#dtPatientAdmission_Time').fill('12:45');
  await page1.locator('#txtPrimaryDiagnosis').click();
  await page1.locator('#txtPrimaryDiagnosis').fill('OTB');
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.locator('li').filter({ hasText: 'Documentation Interdisciplinary Documentation Business Letters DRG' }).locator('i').first().click();
  await page1.getByRole('link', { name: 'Tasks' }).click();
  await page1.getByRole('link', { name: 'Add' }).click();
  await page1.locator('#ddlTaskItemId').selectOption('3016');
  await page1.locator('#ddlAssignToId').selectOption('1693662');
  await expect(page1.locator('#ecStartOn').getByRole('cell', { name: ':18 AM (CT)' })).toBeVisible();
  await expect(page1.getByRole('cell', { name: '7:18 AM (CT)', exact: true }).nth(1)).toBeVisible();
  await page1.locator('#ddlStatus').selectOption('4467');
  await page1.locator('#cbNotifyCreatorWhenAssigned').check();
  await page1.locator('#cbNotifyCreatorWhenPastDue').check();
  await page1.locator('#cbNotifyCreatorWhenCompleted').check();
  await page1.locator('#cbNotifyOwnerWhenAssigned').check();
  await page1.locator('#cbNotifyOwnerWhenPastDue').check();
  await page1.locator('#cbNotifyOwnerWhenCompleted').check();
  await page1.getByRole('button', { name: 'Save' }).click();
  await expect(page1.getByRole('cell', { name: '9/14/2024 12:35 PM (CT) 9/11/2024 1:35 AM (CT)', exact: true })).toBeVisible();
});