import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://pv02.extendedcare.health/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Log In' }).click();
  const page1 = await page1Promise;
  await page1.locator('#UserNameTextBox').fill('srikannan');
  await page1.locator('#PasswordTextBox').click();
  await page1.locator('#PasswordTextBox').fill('Organization=20');
  await page1.getByText('Log In').click();
  await page1.getByRole('link', { name: ' Home' }).click();
  await page1.getByRole('link', { name: 'Change Organization' }).click();
  await page1.getByRole('link', { name: 'CM Automation Hospital', exact: true }).click();
  await page1.getByRole('link', { name: ' Manage' }).click();
  await page1.getByRole('link', { name: 'Patients ' }).click();
  await page1.getByRole('link', { name: 'Patients Default View' }).click();
  await page1.getByRole('link', { name: 'Add a Patient' }).click();
  await page1.getByLabel('MRN:').click();
  await page1.getByLabel('MRN:').fill('AUD123');
  await page1.getByLabel('First Name:', { exact: true }).click();
  await page1.getByLabel('First Name:', { exact: true }).fill('test');
  await page1.getByLabel('Last Name:', { exact: true }).click();
  await page1.getByLabel('Last Name:', { exact: true }).fill('Audit 1');
  await page1.locator('#ECINCalendarDateOfBirth_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').locator('#Cell21').click();
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('link', { name: '' }).click();
  await page1.locator('#txtHospitalAdmissionID').click();
  await page1.locator('#txtHospitalAdmissionID').fill('Audit123');
  await page1.locator('#dtPatientAdmission_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '16', exact: true }).click();
  await page1.locator('#dtPatientAdmission_Time').click();
  await page1.locator('#dtPatientAdmission_Time').fill('12:45 AM');
  await page1.locator('#txtPrimaryDiagnosis').click();
  await page1.locator('#txtPrimaryDiagnosis').fill('Test1');
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByTitle('Create a new audit').click();
  await page1.locator('#ddlAuditType').selectOption('13568');
  await page1.locator('#lnkAddChartRequest').click();
  await page1.locator('#ddlChartRequestType').selectOption('25862');
  await page1.goto('https://pv02.extendedcare.health/professional/Manage/Audits/ChartRequestEditor.aspx');
  await page1.goto('https://pv02.extendedcare.health/professional/Manage/Audits/ChartRequestNoteEditor.aspx');
  await page1.locator('#txtNotes').click();
  await page1.locator('#txtNotes').fill('testAudiet123456789');
  await page1.goto('https://pv02.extendedcare.health/professional/Manage/Audits/ChartRequestEditor.aspx');
  await expect(page1.locator('#dgChartRequestNotes_ctl02_LinkChartRequestNote')).toContainText('10/14/2024 12:45 PM (CT)');
  await page1.goto('https://pv02.extendedcare.health/professional/Manage/Audits/AuditDetails.aspx');
  await page1.goto('https://pv02.extendedcare.health/professional/Manage/Audits/AuditNoteEditor.aspx');
  await page1.locator('#txtNotes').click();
  await page1.locator('#txtNotes').fill('Auditnotes123test');
  await page1.goto('https://pv02.extendedcare.health/professional/Manage/Audits/AuditDetails.aspx');
  await expect(page1.locator('#dgAuditNotes_ctl02_LinkAuditNote')).toContainText('10/14/2024 1:23 PM (CT)');
  await page1.getByRole('button', { name: 'Save' }).click();
});