import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://pv02.extendedcare.health/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Log In' }).click();
  const page1 = await page1Promise;
  await page1.locator('#UserNameTextBox').fill('srikannan');
  await page1.locator('#PasswordTextBox').click();
  await page1.locator('#PasswordTextBox').fill('Organization=20');
  await page1.getByText('Log In').click();
  await page1.goto('https://pv02.extendedcare.health/professional/AngularPages/Home/Dashboard.aspx/home/dashboard');
  await page1.getByRole('link', { name: ' Home' }).click();
  await page1.getByRole('link', { name: 'Change Organization' }).click();
  await page1.getByRole('link', { name: 'CM Automation Hospital', exact: true }).click();
  await page1.getByRole('link', { name: ' Manage' }).click();
  await page1.getByRole('link', { name: 'Patients ' }).click();
  await page1.getByRole('link', { name: 'Patients Default View' }).click();
  await page1.getByRole('link', { name: 'Add a Patient' }).click();
  await page1.getByLabel('MRN:').click();
  await page1.getByLabel('MRN:').fill('Task123');
  await page1.getByLabel('First Name:', { exact: true }).click();
  await page1.getByLabel('First Name:', { exact: true }).fill('task test');
  await page1.getByLabel('Last Name:', { exact: true }).click();
  await page1.getByLabel('Last Name:', { exact: true }).fill('A test');
  await page1.locator('#ECINCalendarDateOfBirth_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').locator('#selYear').selectOption('65');
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '13', exact: true }).click();
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('link', { name: '' }).click();
  await page1.locator('#txtHospitalAdmissionID').click();
  await page1.locator('#txtHospitalAdmissionID').press('CapsLock');
  await page1.locator('#txtHospitalAdmissionID').fill('TASDKadm132');
  await page1.locator('#dtPatientAdmission_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '15', exact: true }).click();
  await page1.locator('#dtPatientAdmission_Time').click();
  await page1.locator('#dtPatientAdmission_Time').fill('03:45 AM');
  await page1.locator('#txtPrimaryDiagnosis').click();
  await page1.locator('#txtPrimaryDiagnosis').fill('tASK123');
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('link', { name: ' Configure' }).click();
  await page1.getByRole('link', { name: 'Workflow ' }).click();
  await page1.getByRole('link', { name: 'Task Library' }).click();
  await page1.getByRole('link', { name: 'Add Task Item' }).click();
  await page1.getByLabel('Yes').check();
  await page1.locator('#txtTiName').click();
  await page1.locator('#txtTiName').fill('TEst Task');
  await page1.locator('#txtDescription').click();
  await page1.locator('#txtDescription').fill('Desc123task');
  await page1.locator('#ddlDefaultStatus').selectOption('1295');
  await page1.locator('#eneDefaultStartOnOffsetDays_Number').click();
  await page1.locator('#eneDefaultStartOnOffsetDays_Number').fill('0');
  await page1.locator('#eneDefaultStartOnOffsetHrs_Number').click();
  await page1.locator('#eneDefaultStartOnOffsetHrs_Number').fill('0');
  await page1.locator('#eneDefaultDueDateOffsetDays_Number').click();
  await page1.locator('#eneDefaultDueDateOffsetDays_Number').fill('0');
  await page1.locator('#eneDefaultDueDateOffsetHrs_Number').click();
  await page1.locator('#eneDefaultDueDateOffsetHrs_Number').fill('0');
  await page1.locator('#cbDefaultNotifyCreatorWhenAssigned').check();
  await page1.locator('#cbDefaultNotifyOwnerWhenAssigned').check();
  await page1.locator('#cbDefaultNotifyCreatorWhenPastDue').check();
  await page1.locator('#cbDefaultNotifyOwnerWhenPastDue').check();
  await page1.locator('#cbDefaultNotifyCreatorWhenCompleted').check();
  await page1.locator('#cbDefaultNotifyOwnerWhenCompleted').check();
  await page1.locator('#txtAssignedMessagePager_ddlIVIT_ddl_variables').selectOption('TaskID');
  await page1.locator('#txtAssignedMessagePager_ddlIVIT_btn_add').click();
  await page1.locator('#txtAssignedMessageEmail_ddlIVIT_ddl_variables').selectOption('TaskCompletedOn');
  await page1.locator('#txtAssignedMessageEmail_ddlIVIT_btn_add').click();
  await page1.locator('#txtAssignedMessageEmail_ddlIVIT_ddl_variables').selectOption('ActualTime');
  await page1.locator('#txtAssignedMessageEmail_ddlIVIT_btn_add').click();
  await page1.locator('#txtAssignedMessageEmail_ddlIVIT_ddl_variables').selectOption('ProjectedTime');
  await page1.locator('#txtAssignedMessageEmail_ddlIVIT_btn_add').click();
  await page1.locator('#txtAssignedMessageSysAlert_ddlIVIT_ddl_variables').selectOption('ActualTime');
  await page1.locator('#txtAssignedMessageSysAlert_ddlIVIT_btn_add').click();
  await page1.locator('#txtAssignedMessageSysAlert_ddlIVIT_ddl_variables').selectOption('TaskCompletedOn');
  await page1.locator('#txtAssignedMessageSysAlert_ddlIVIT_btn_add').click();
  await page1.locator('#txtAssignedMessageSysAlert_ddlIVIT_ddl_variables').selectOption('ProjectedTime');
  await page1.locator('#txtAssignedMessageSysAlert_ddlIVIT_btn_add').click();
  await page1.locator('#txtCompletedMessagePager_ddlIVIT_ddl_variables').selectOption('ActualTime');
  await page1.locator('#txtCompletedMessagePager_txtTextArea').click();
  await page1.locator('#txtCompletedMessagePager_txtTextArea').fill('$[ActualTime]$$[TaskCompletedOn]$$[ProjectedTime]$');
  await page1.locator('#txtCompletedMessageEmail_txtTextArea').click();
  await page1.locator('#txtCompletedMessageEmail_txtTextArea').fill('$[ActualTime]$$[TaskCompletedOn]$$[ProjectedTime]$');
  await page1.locator('#txtCompletedMessageSysAlert_txtTextArea').click();
  await page1.locator('#txtCompletedMessageSysAlert_txtTextArea').fill('$[ActualTime]$$[TaskCompletedOn]$$[ProjectedTime]$');
  await page1.locator('#txtPastDueMessagePager_txtTextArea').click();
  await page1.locator('#txtPastDueMessagePager_txtTextArea').fill('$[ActualTime]$$[TaskCompletedOn]$$[ProjectedTime]$');
  await page1.locator('#txtPastDueMessageEmail_txtTextArea').click();
  await page1.locator('#txtPastDueMessageEmail_txtTextArea').fill('$[ActualTime]$$[TaskCompletedOn]$$[ProjectedTime]$');
  await page1.locator('#txtPastDueMessageSysAlert_txtTextArea').click();
  await page1.locator('#txtPastDueMessageSysAlert_txtTextArea').fill('$[ActualTime]$$[TaskCompletedOn]$$[ProjectedTime]$');
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('link', { name: ' Manage' }).click();
  await page1.getByRole('link', { name: 'Patients ' }).click();
  await page1.getByRole('link', { name: 'Patients Default View' }).click();
  await page1.locator('li').filter({ hasText: 'Documentation Avoidable Days' }).locator('i').first().click();
  await page1.getByRole('link', { name: 'Tasks' }).click();
  await page1.getByRole('link', { name: 'Add' }).click();
  await page1.locator('#ddlTaskItemId').selectOption('3564');
  await expect(page1.locator('#ecStartOn_Date')).toBeVisible();
  await expect(page1.locator('#ecStartOn').getByRole('cell', { name: ':54 PM (CT)' })).toBeVisible();
  await expect(page1.locator('input[name="ecDueBy\\$Date"]')).toBeVisible();
  await expect(page1.getByRole('cell', { name: '1:54 PM (CT)', exact: true }).nth(1)).toBeVisible();
  await page1.locator('#ddlAssignToId').selectOption('1684993');
  await page1.getByRole('button', { name: 'Save' }).click();
  await expect(page1.locator('#dgMain_ctl03_lblDueDateCST')).toBeVisible();
  await expect(page1.locator('#dgMain_ctl03_lblStartOnDateCST')).toBeVisible();
  await expect(page1.getByRole('cell', { name: '10/14/2024 1:57 PM (CT)', exact: true }).first()).toBeVisible();
  await expect(page1.locator('#dgTaskHistoryList > tbody > tr:nth-child(2) > td:nth-child(4)')).toBeVisible();
  await page1.getByRole('button', { name: 'Save' }).click();
});