import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://pv02.extendedcare.health/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Log In' }).click();
  const page1 = await page1Promise;
  await page1.locator('#UserNameTextBox').fill('srikannan');
  await page1.locator('#PasswordTextBox').click();
  await page1.locator('#PasswordTextBox').fill('Organization=20');
  await page1.getByText('Log In').click();
  await page1.getByRole('link', { name: ' Home' }).click();
  await page1.getByRole('link', { name: 'Change Organization' }).click();
  await page1.getByRole('link', { name: 'CM Automation Hospital', exact: true }).click();
  await page1.getByRole('link', { name: ' Manage' }).click();
  await page1.getByRole('link', { name: 'Patients ' }).click();
  await page1.getByRole('link', { name: 'Patients Default View' }).click();
  await page1.getByRole('link', { name: 'Add a Patient' }).click();
  await page1.getByLabel('MRN:').click();
  await page1.getByLabel('MRN:').fill('DRG123');
  await page1.getByLabel('First Name:', { exact: true }).click();
  await page1.getByLabel('First Name:', { exact: true }).fill('Test');
  await page1.getByLabel('Last Name:', { exact: true }).click();
  await page1.getByLabel('Last Name:', { exact: true }).fill('DRG12345');
  await page1.locator('#ECINCalendarDateOfBirth_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').locator('#selYear').selectOption('108');
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '9', exact: true }).click();
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('link', { name: '' }).click();
  await page1.locator('#txtHospitalAdmissionID').click();
  await page1.locator('#txtHospitalAdmissionID').fill('DRGStart123');
  await page1.locator('#dtPatientAdmission_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '15', exact: true }).click();
  await page1.locator('#dtPatientAdmission_Time').click();
  await page1.locator('#dtPatientAdmission_Time').fill('12:45 PM');
  await page1.locator('#txtPrimaryDiagnosis').click();
  await page1.locator('#txtPrimaryDiagnosis').fill('Cholera');
  await page1.getByRole('button', { name: 'Save' }).click();
  await page1.locator('li').filter({ hasText: 'Documentation Avoidable Days' }).locator('i').first().click();
  await page1.getByRole('link', { name: 'DRG Documentation' }).click();
  await expect(page1.locator('#ecalDRGReviewDateTime_Date')).toBeVisible();
  await expect(page1.locator('#ecalDRGReviewDateTime').getByRole('cell', { name: ':21 PM (CT)' })).toBeVisible();
  await expect(page1.locator('#ecalNextDRGDate_Date')).toBeVisible();
  await expect(page1.locator('#ecalNextDRGDate').getByRole('cell', { name: ':21 PM (CT)' })).toBeVisible();
  await page1.locator('#ddlDRGStatus').selectOption('1276');
  await page1.locator('#lnkDocumentationComments').click();
  await page1.locator('#ddDocumentationType').selectOption('Concurrent');
  await page1.locator('#txtComments').click();
  await page1.locator('#txtComments').fill('DRG teststart123');
  await page1.getByRole('button', { name: 'Save' }).click();
  await expect(page1.getByRole('cell', { name: 'M R, Srikannan', exact: true })).toBeVisible();
  await expect(page1.getByRole('cell', { name: '10/14/2024 2:22 PM (CT)', exact: true })).toBeVisible();
  await page1.locator('#lnkQueryPage').click();
  await page1.locator('#cbPrimaryQueryPage').check();
  await page1.locator('#ddlQueryType').selectOption('916');
  await expect(page1.locator('#ecQueryDate_Date')).toBeVisible();
  await expect(page1.locator('#ecQueryDate_Time')).toBeVisible();
  await page1.locator('#ecNextQueryDate_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '17', exact: true }).click();
  await page1.locator('#ecNextQueryDate_Time').click();
  await page1.locator('#ecNextQueryDate_Time').fill('5:45 PM');
  await page1.locator('#ddQueryStatus').selectOption('AUTO Complete');
  await page1.locator('#ddQueryCommunicationMethod').selectOption('711');
  await page1.locator('#lnkQueryCommentAdd').click();
  await page1.locator('#txtComments').fill('CMT DG DRG');
  await page1.getByRole('button', { name: 'Save' }).click();
  await expect(page1.getByRole('cell', { name: 'M R, Srikannan', exact: true })).toBeVisible();
  await expect(page1.getByRole('cell', { name: '10/14/2024 2:24 PM (CT)', exact: true })).toBeVisible();
  await page1.locator('#ecPhysicianDateTime_CalImg').click();
  await page1.frameLocator('iframe[name="CalIFrame"]').getByRole('cell', { name: '15', exact: true }).click();
  await page1.locator('#ecPhysicianDateTime_Time').click();
  await page1.locator('#ecPhysicianDateTime_Time').fill('12:45 PM');
  await page1.locator('#txtComments').click();
  await page1.locator('#txtComments').fill('test');
  await page1.getByRole('button', { name: 'Save' }).click();
  await expect(page1.getByRole('link', { name: 'AUTO Query Type' })).toBeVisible();
  await expect(page1.locator('#dgQuery').getByRole('cell', { name: 'M R, Srikannan' })).toBeVisible();
  await expect(page1.getByRole('cell', { name: '10/14/2024 2:23 PM (CT)', exact: true })).toBeVisible();
  await expect(page1.getByRole('cell', { name: '10/17/2024 5:45 PM (CT)', exact: true })).toBeVisible();
  await expect(page1.getByRole('cell', { name: 'AUTO Email', exact: true })).toBeVisible();
  await expect(page1.getByRole('cell', { name: 'AUTO Complete', exact: true })).toBeVisible();
  await page1.getByRole('button', { name: 'Save' }).click();
});