import { test, expect } from '@playwright/test';
import { LoginPage } from '../../pages/PageLogin_111';
import { LIB } from '../../bizLibs/lib';
import { PatientdefaultviewPage } from '../../pages/patientdefaultviewpage_631';
import { PatientdetailsPage } from '../../pages/patientdetailspage_52';
import { AdmissiondetailsPage } from '../../pages/admissiondetailspage_54';
import { EditPaymentSource } from '../../pages/EditPaymentSourcePage_165';
import { AdmissionFinancialInformationPage } from '../../pages/AdmissionFinancialInformationPage_55';
import { ApplicationNavigator } from '../../pages/ApplicationNavigator';
import { ManageContextNavigator } from '../../pages/ManageContextNavigator';
import { Diagnoses } from '../../pages/DiagnosesPage_1017';
import { CodeEditor } from '../../pages/CodeEditorPage_1020';
import { CodeLookUp } from '../../pages/CodeLookUpPage_1022';
import { Procedure } from '../../pages/ProcedurePage_1019';
import { SavedDays } from '../../pages/SavedDaysPage_578';
import { EditSavedDays } from '../../pages/EditSavedDaysPage_579';
import { PayorAuthorizations } from '../../pages/PayorAuthorizationsPage_745';
import { PayorAuthorization } from '../../pages/PayorAuthorizationPage_812';
import { AddEditUMNotes } from '../../pages/AddEditUMNotesPage_746'
import { DRGDocumentationLetters } from '../../pages/DRGDocumentationLettersPage_918';
import { DRGDocumentationLettersGenerator } from '../../pages/DRGDocumentationLettersGeneratorPage_919';
const { user, password } = process.env;
const timeZone = 'CT';
const format = '12hr';

test('CM- HCA to Support7', async ({ page }) => {
  await page.goto('https://pv02.extendedcare.health/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Log In' }).click();
  const page1 = await page1Promise;
  await page1.locator('#UserNameTextBox').click();
  await page1.locator('#UserNameTextBox').fill('srikannan');
  await page1.locator('#PasswordTextBox').click();
  await page1.locator('#PasswordTextBox').fill('Organization=20');
  await page1.getByText('Log In').click();
  await page1.getByRole('link', { name: ' Home' }).click();
  await page1.getByRole('link', { name: 'Change Organization' }).click();
  await page1.getByRole('link', { name: '`Allscripts QA Hospital 124 (' }).click();
  await page1.getByRole('link', { name: ' Manage' }).click();
  await page1.getByRole('link', { name: 'Patient Favorites ' }).click();
  await page1.getByRole('link', { name: 'M R, SRIKANNAN (974246)' }).click();
  await page1.getByRole('link', { name: 'TEST12345 (7/9/2024)' }).click();
  await page1.getByTitle('Create a new audit').click();
  await page1.locator('#ddlAuditType').selectOption('13093');
  await page1.locator('#ddlPlanDescription').selectOption('307844815');
  await page1.locator('#ddlAuditDepartment').selectOption('41303');
  await page1.locator('#lnkAddChartRequest').click();
  await page1.locator('#ddlChartRequestType').selectOption('25862');
  await page1.locator('#txtNotes').click();
  await page1.locator('#txtNotes').fill('testAudiet123456789');
 // await expect(page1.locator('#dgChartRequestNotes_ctl02_LinkChartRequestNote')).toContainText('10/14/2024 12:45 PM (CT)');
  await page1.locator('#txtNotes').click();
  await page1.locator('#txtNotes').fill('Auditnotes123test');
  await page1.getByRole('button', { name: 'Save' }).click();
  await expect(page1.locator('#dgAuditNotes_ctl02_LinkAuditNote')).toContainText('10/14/2024 1:23 PM (CT)');

});